apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service
  template:
    metadata:
      labels:
        app: department-service
    spec:
      containers:
        - name: department-service
          image: ravikantshukla/department-service
          ports:
            - containerPort: 8092
          env:
            - name: REGISTRY_URL
              value: http://discovery-service:8061/eureka
            - name: CONFIG_URL
              value: http://config-service:8088
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: department-service
spec:
  selector:
    app: department-service
  ports:
    - port: 8092
      targetPort: 8092